// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuG2cTUGWyPIXSP8gaX70U6piQwzKs5hM',
    appId: '1:649487202902:web:0bfdb99bc3fb847fdb99f7',
    messagingSenderId: '649487202902',
    projectId: 'ascend-99a85',
    authDomain: 'ascend-99a85.firebaseapp.com',
    storageBucket: 'ascend-99a85.firebasestorage.app',
    measurementId: 'G-V7093L250Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwvtNkjq-5Hd5uqJXw5_rP4GmTZClI7yU',
    appId: '1:649487202902:android:9d087ed51dcee34adb99f7',
    messagingSenderId: '649487202902',
    projectId: 'ascend-99a85',
    storageBucket: 'ascend-99a85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDRc8tBb7YiBRQ-UoPKSbH28pW4-GFBgQ',
    appId: '1:649487202902:ios:895e643c68b5de03db99f7',
    messagingSenderId: '649487202902',
    projectId: 'ascend-99a85',
    storageBucket: 'ascend-99a85.firebasestorage.app',
    iosBundleId: 'com.example.ascendBible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDRc8tBb7YiBRQ-UoPKSbH28pW4-GFBgQ',
    appId: '1:649487202902:ios:895e643c68b5de03db99f7',
    messagingSenderId: '649487202902',
    projectId: 'ascend-99a85',
    storageBucket: 'ascend-99a85.firebasestorage.app',
    iosBundleId: 'com.example.ascendBible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuG2cTUGWyPIXSP8gaX70U6piQwzKs5hM',
    appId: '1:649487202902:web:0f4854f2a5135429db99f7',
    messagingSenderId: '649487202902',
    projectId: 'ascend-99a85',
    authDomain: 'ascend-99a85.firebaseapp.com',
    storageBucket: 'ascend-99a85.firebasestorage.app',
    measurementId: 'G-WK0PJZFEYP',
  );
}
